/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Q1FFzknVeY9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { PaletteIcon, ChevronsUpDownIcon } from "lucide-react";

export function DropdownTheme({ ...props }) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="w-full justify-between">
          <div className="flex items-center gap-2">
            <PaletteIcon className="h-5 w-5" />
          </div>
          {/* <ChevronsUpDownIcon className="h-4 w-4 opacity-50" /> */}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="" {...props}></DropdownMenuContent>
    </DropdownMenu>
  );
}
