/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vc2CX974Dd8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button'
import { Card } from '../ui/card'

export function ExploreCard() {
  return (
    <div className="px-6 py-8 ">
      <Card className=" rounded-lg overflow-hidden shadow-lg ">
        <div className="p-8 md:p-12 lg:p-16">
          <h2 className="text-4xl text-center md:text-5xl lg:text-6xl font-bold text-white mb-4">
            Explore the Gemini 1.5 AI Models
          </h2>
          <p className="text-lg md:text-xl text-center lg:text-2xl text-gray-200 mb-8">
            Unlock the power of advanced AI models designed to revolutionize
            your workflow. Discover Gemini 1.5, the cutting-edge suite of AI
            assistants that can tackle a wide range of tasks with unparalleled
            precision and efficiency.
          </p>
        </div>
      </Card>
    </div>
  )
}
