/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0Qge4FfLucI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardHeader, CardContent, Card } from '@/components/ui/card'
import { AvatarImage, AvatarFallback, Avatar } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { JSX, SVGProps } from 'react'

export function ExploreComponent() {
  return (
    <div className="flex flex-col h-screen  text-gray-50">
      <div className="flex-1 overflow-auto">
        <div className="px-6 py-8">
          <h2 className="text-2xl font-semibold mb-6 text-gray-900">
            Explorar Modelos
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card className="bg-gray-900 border border-gray-200 border-gray-800 rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 dark:border-gray-800">
              <CardHeader>
                <div className="relative">
                  <img
                    alt="Model Image"
                    className="rounded-t-lg object-cover w-full aspect-video"
                    height={200}
                    src="/placeholder.svg"
                    width={300}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-gray-900 to-transparent" />
                  <div className="absolute bottom-4 left-4 text-white">
                    <h3 className="text-xl font-semibold">
                      Creative Writing Assistant
                    </h3>
                    <p className="text-sm">
                      Enhance your writing with this powerful AI model.
                    </p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-8 h-8 border border-gray-200 border-gray-700 dark:border-gray-800">
                    <AvatarImage
                      alt="Creator Avatar"
                      src="/placeholder-user.jpg"
                    />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-gray-400">John Doe</span>
                </div>
                <Button size="icon" variant="ghost">
                  <PlusIcon className="w-5 h-5" />
                </Button>
              </CardContent>
            </Card>
            <Card className="bg-gray-900 border border-gray-200 border-gray-800 rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 dark:border-gray-800">
              <CardHeader>
                <div className="relative">
                  <img
                    alt="Model Image"
                    className="rounded-t-lg object-cover w-full aspect-video"
                    height={200}
                    src="/placeholder.svg"
                    width={300}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-gray-900 to-transparent" />
                  <div className="absolute bottom-4 left-4 text-white">
                    <h3 className="text-xl font-semibold">
                      Productivity Booster
                    </h3>
                    <p className="text-sm">
                      Stay focused and organized with this AI assistant.
                    </p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-8 h-8 border border-gray-200 border-gray-700 dark:border-gray-800">
                    <AvatarImage
                      alt="Creator Avatar"
                      src="/placeholder-user.jpg"
                    />
                    <AvatarFallback>SA</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-gray-400">Sarah Adams</span>
                </div>
                <Button size="icon" variant="ghost">
                  <PlusIcon className="w-5 h-5" />
                </Button>
              </CardContent>
            </Card>
            <Card className="bg-gray-900 border border-gray-200 border-gray-800 rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 dark:border-gray-800">
              <CardHeader>
                <div className="relative">
                  <img
                    alt="Model Image"
                    className="rounded-t-lg object-cover w-full aspect-video"
                    height={200}
                    src="/placeholder.svg"
                    width={300}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-gray-900 to-transparent" />
                  <div className="absolute bottom-4 left-4 text-white">
                    <h3 className="text-xl font-semibold">
                      Research Assistant
                    </h3>
                    <p className="text-sm">
                      Streamline your research process with this AI tool.
                    </p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-4 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-8 h-8 border border-gray-200 border-gray-700 dark:border-gray-800">
                    <AvatarImage
                      alt="Creator Avatar"
                      src="/placeholder-user.jpg"
                    />
                    <AvatarFallback>MK</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-gray-400">Michael Kim</span>
                </div>
                <Button size="icon" variant="ghost">
                  <PlusIcon className="w-5 h-5" />
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}

function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
