/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/o2uPnU3NrJS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function SectionHero() {
  return (
    <section className="w-full py-24 md:py-32 lg:py-40 bg-gradient-to-r from-[#0077b6] to-[#00a8e8]">
      <div className="container px-4 md:px-6 flex flex-col items-center text-center">
        <div className="max-w-4xl space-y-6">
          <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight text-primary-foreground">
            Desbloqueie seu potencial com nossa equipe dinâmica
          </h1>
          <p className="text-xl md:text-2xl text-primary-foreground">
            Junte-se a uma empresa que valoriza a inovação, a colaboração e o crescimento pessoal. Descubra seu emprego
            dos sonhos hoje.
          </p>
          <div>
            <Link
              className="inline-flex h-12 items-center justify-center rounded-md bg-[#25D366] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#128C7E] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              href="#"
              prefetch={false}
            >
              <PhoneIcon className="mr-2 h-5 w-5" />
              WhatsApp
            </Link>
          </div>
        </div>
        <div className="mt-12 w-full max-w-5xl">
          <img
            src="/placeholder.svg"
            width="1200"
            height="600"
            alt="Ilustração do Herói"
            className="mx-auto animate-float"
          />
        </div>
      </div>
    </section>
  )
}

function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
